apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
      matchLabels:
        app: demo1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: demo1
          image: demo1:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
